### ISSUE TITLE
`kele--get-host-for-context` returns incorrect value if context's server has a port

### ISSUE THREAD

**Issue by jinnovation** [jinnovation/kele.el#61]
For example, the following fails:
```yaml
clusters:
- cluster:
    proxy-url: http://proxy.example.org:3128
    server: https://123.456.789.0:9999
  name: development-cluster
```
